//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DenyClusterAdminBindingConfig) DeepCopyInto(out *DenyClusterAdminBindingConfig) {
	*out = *in
	if in.ExcludeServiceAccounts != nil {
		in, out := &in.ExcludeServiceAccounts, &out.ExcludeServiceAccounts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DenyClusterAdminBindingConfig.
func (in *DenyClusterAdminBindingConfig) DeepCopy() *DenyClusterAdminBindingConfig {
	if in == nil {
		return nil
	}
	out := new(DenyClusterAdminBindingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.RequireDefaultDenyIngress != nil {
		in, out := &in.RequireDefaultDenyIngress, &out.RequireDefaultDenyIngress
		*out = new(bool)
		**out = **in
	}
	if in.RequireDefaultDenyEgress != nil {
		in, out := &in.RequireDefaultDenyEgress, &out.RequireDefaultDenyEgress
		*out = new(bool)
		**out = **in
	}
	if in.ExemptNamespaces != nil {
		in, out := &in.ExemptNamespaces, &out.ExemptNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySpec.
func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACSpec) DeepCopyInto(out *RBACSpec) {
	*out = *in
	if in.DenyWildcardVerbs != nil {
		in, out := &in.DenyWildcardVerbs, &out.DenyWildcardVerbs
		*out = new(bool)
		**out = **in
	}
	if in.DenyWildcardResources != nil {
		in, out := &in.DenyWildcardResources, &out.DenyWildcardResources
		*out = new(bool)
		**out = **in
	}
	if in.DenyClusterAdminBinding != nil {
		in, out := &in.DenyClusterAdminBinding, &out.DenyClusterAdminBinding
		*out = new(DenyClusterAdminBindingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RequireNamespacedRoles != nil {
		in, out := &in.RequireNamespacedRoles, &out.RequireNamespacedRoles
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACSpec.
func (in *RBACSpec) DeepCopy() *RBACSpec {
	if in == nil {
		return nil
	}
	out := new(RBACSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationSpec) DeepCopyInto(out *RemediationSpec) {
	*out = *in
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(int32)
		**out = **in
	}
	if in.RequireApprovalFor != nil {
		in, out := &in.RequireApprovalFor, &out.RequireApprovalFor
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationSpec.
func (in *RemediationSpec) DeepCopy() *RemediationSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustPolicy) DeepCopyInto(out *ZeroTrustPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustPolicy.
func (in *ZeroTrustPolicy) DeepCopy() *ZeroTrustPolicy {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeroTrustPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustPolicyList) DeepCopyInto(out *ZeroTrustPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZeroTrustPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustPolicyList.
func (in *ZeroTrustPolicyList) DeepCopy() *ZeroTrustPolicyList {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeroTrustPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustPolicySpec) DeepCopyInto(out *ZeroTrustPolicySpec) {
	*out = *in
	if in.RBAC != nil {
		in, out := &in.RBAC, &out.RBAC
		*out = new(RBACSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(NetworkPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Remediation != nil {
		in, out := &in.Remediation, &out.Remediation
		*out = new(RemediationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustPolicySpec.
func (in *ZeroTrustPolicySpec) DeepCopy() *ZeroTrustPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustPolicyStatus) DeepCopyInto(out *ZeroTrustPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustPolicyStatus.
func (in *ZeroTrustPolicyStatus) DeepCopy() *ZeroTrustPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
